import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SidebarLayout from "@/components/sidebar/SidebarLayout";
import SidebarNotes from "@/components/sidebar/SidebarNotes";
import SidebarTags from "@/components/sidebar/SidebarTags";
import { NavProvider } from "@/lib/context/NavContext";
import PopupHost from "@/lib/context/PopupHost";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
        >
          <div className="flex">
            <NavProvider>
              <SidebarLayout>
                <SidebarNotes />
                <SidebarTags />
              </SidebarLayout>
              <main>{children}</main>
              <PopupHost />
            </NavProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
